/* eslint-disable @next/next/no-img-element */
import moment from "moment";
import Head from "next/head";
import Footer from "../../components/Footer";
import FormCheckout from "../../components/FormCheckout";
import Navbar from "../../components/Navbar";
import { getData } from "../../utils/fetchData";
import { formatDate } from "../../utils/formatDate";
import {useRouter} from 'next/navigation'


export default function Dashboard({ data }) {

  return (
    <>
      <Head>
        <title>Semina || Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>

      <section className="bg-navy">
        <div className="checkout container">
          <div className="text-center checkout-title">Invest In Yourself</div>
          <section className="d-flex flex-column justify-content-center align-items-center px-5">
            {data.map((data) => (
              <div
            
                className="event-details container d-flex flex-wrap justify-content-lg-center align-items-center gap-5 border p-3 rounded"
                key={data._id}
              >
                <div className="d-flex flex-column gap-3 mx-5">
                  <h5 className=''>{data.historyEvent.title}</h5>

                  <div className="d-flex align-items-center gap-3">
                    <img src="/icons/ic-marker-white.svg" alt="" />
                    <span>{data.historyEvent.venueName}</span>
                  </div>
                  <div className="d-flex align-items-center gap-3">
                    <img src="/icons/ic-time-white.svg" alt="" />
                    <span>
                      {moment(data.historyEvent.date).format("HH.MM A")}
                    </span>
                  </div>
                  <div className="d-flex align-items-center gap-3">
                    <img src="/icons/ic-calendar-white.svg" alt="" />
                    <span>{formatDate(data.historyEvent.date)}</span>
                  </div>
                </div>
                <div className="total-price mx-auto px-5">
                  {data.totalPay === 0 ? "free" : `$ ${data.totalPay}`}
                </div>
              </div>
            ))}
          </section>
        </div>
      </section>
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {

  if (!context.req.cookies.token) return {
    redirect: {
      destination: '/signin',
      permanent: true
    }
  }
  
  const req = await getData(`/api/v1/orders`, {}, context.req.cookies.token);

  const res = req.data;

  // console.log('token >>>>>>>>>>>>>');
  // console.log(context.req.cookies.token);

  return {
    props: { data: res },
  };
}
